AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**
    - lib/tasks/sample.rake
  RunRailsCops: true

ClassLength:
  Max: 300

MethodLength:
  Max: 50

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 38

Style/GlobalVars:
  AllowedVariables: [$evm]

# disabled to allow hyphen in gem name
Style/FileName:
  Enabled: false